services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: express_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5332"

  express-api:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: admin
      PGPASSWORD: password
      PGDATABASE: express_api
      PGPORT: 5332

